name: 📦 Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  Publish:
    env:
      jdk: 16
      maven_cmd: clean package
      ref_main: "main"
      ref_dev: "dev"
      files: |
        ./project/target/jdavcspeaker-jar-with-dependencies.jar
    runs-on: ubuntu-latest
    steps:
      - name: 👉 Release Version
        id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}
          default_bump: "minor"
          custom_release_rules: "breaking:major:💣 Breaking Changes,feat:minor:✨ Features,fix:patch:💣 Bug Fixes,docs:patch:📰 Docs,chore:patch:🎨 Chore,pref:patch:🎈 Performance improvements,refactor:patch:🧹 Refactoring,build:patch:🔍 Build,ci:patch:🔍 CI,revert:patch:⏪ Revert,style:patch:🧹 Style,test:patch:👀 Test"
      - name: 📻 Setup JDK16
        uses: actions/setup-java@v3.0.0
        with:
          distribution: "zulu"
          java-version: ${{ env.jdk }}
      - name: 📦 Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          path: project
      - name: ⌛ Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/caches
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 📦 Package
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        run: |
          cd ./project
          mvn ${{ env.maven_cmd }}
      - name: 🗃️ Publish Release (main)
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        if: github.ref_name == env.ref_main
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ env.project_version }}
          files: ${{ env.files }}
      - name: 🗃️ Publish Release (dev)
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        if: github.ref_name == env.ref_dev
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          tag_name: ${{ env.project_version }}
          files: ${{ env.files }}
